
export let attributeMap = [

  /*
  ==========================================
                   WEAPONS
  ==========================================
  */
  {
    name: "Weapon Range",
    label: "Range",
    description: "Increases effective range of all weapons",
    value: "1",
    template: "+{}%",
    color: "#a6cee3"
  }, {
    name: "Laser Duration",
    label: "Laser Duration",
    description: "Reduces burn duration of lasers",
    value: "3.75",
    template: "-{}%",
    color: "#1f78b4",
    chassisValues: {
      light: {
        is: '3.75',
        clan: '2.50'
      },
      medium: {
        is: '3.75',
        clan: '2.50'
      },
      heavy: {
        is: '3.75',
        clan: '2.50'
      },
      assault: {
        is: '3.75',
        clan: '2.50'
      },
    }
  }, {
    name: "Weapon Velocity",
    label: "Velocity",
    description: "Increases velocity of ballistic, missile, and PPC projectiles",
    value: "3",
    template: "+{}%",
    color: "#e31a1c"
  }, {
    name: "Weapon Cooldown",
    label: "Cooldown",
    description: "Reduces all weapon cooldowns",
    value: "0.75",
    template: "-{}%",
    color: "#33a02c",
    chassisValues: {
      light: {
        is: '0.75',
        clan: '0.6'
      },
      medium: {
        is: '0.75',
        clan: '0.6'
      },
      heavy: {
        is: '0.75',
        clan: '0.6'
      },
      assault: {
        is: '0.75',
        clan: '0.6'
      },
    }
  }, {
    name: "Missile Crit Damage",
    label: "High Explosive",
    description: "Increases the damage done by missile critical hits against internal structure",
    value: "7.5",
    template: "+{}%",
    color: "#fb9a99"
  }, {
    name: "Gauss Held Time",
    label: "Gauss Charge",
    description: "Increases the duration which a Gauss weapon can be held charged before depleting",
    value: "0.75",
    template: "+{} sec.",
    color: "#cab2d6"
  }, {
    name: "Weapon Heat Gen",
    label: "Heat Gen",
    description: "Reduces the heat generated by all weapons",
    value: "0.75",
    template: "-{}%",
    color: "#fdbf6f",
    chassisValues: {
      light: {
        is: '0.75',
        clan: '0.6'
      },
      medium: {
        is: '0.75',
        clan: '0.6'
      },
      heavy: {
        is: '0.75',
        clan: '0.6'
      },
      assault: {
        is: '0.75',
        clan: '0.6'
      },
    }
  }, {
    name: "Ballistic Ammo",
    label: "Magazine Capacity",
    description: "Provides additional per-ton ammunition for Ballstic weapons",
    value: "8",
    template: "+{}",
    color: "#ff7f00"
  }, {
    name: "Missile Ammo",
    label: "Missile Rack",
    description: "Provides additional per-ton ammunition for Missile weapons",
    value: "1",
    template: "+{}",
    color: "#b15928"
  }, {
    name: "Missile Spread",
    label: "Missile Spread",
    description: "Reduces missile spread",
    value: "2.5",
    template: "+{}%",
    color: "#6a3d9a"
  }, {
    name: "LBX Spread",
    label: "LBX Spread",
    description: "Reduces LB-X autocannon spread",
    value: "5",
    template: "-{}%",
    color: "#ffff99"
  }, {
    name: "Enhanced UAC / RAC",
    label: "Enhanced UAC",
    description: "Reduces jam time for Ultra autocannon; improves jam bar reduction for Rotary autocannon",
    value: "2.5",
    template: "-{}%",
    color: "#b2df8a"
  }, {
    name: "Flamer Ventilation",
    label: "Flamer Ventilation",
    description: "Increases ramped heat dissipation",
    value: "7.5",
    template: "-{}%",
    color: "#ffff99"
  },
  /*
  ==========================================
                  SURVIVAL
  ==========================================
  */
  {
    name: "Armor",
    label: "Armor Hardening",
    description: "Increases armor",
    value: "1.6",
    template: "+{}%",
    color: "#e41a1c",
    chassisValues: {
      light: {
        is: '2.5',
        clan: '2.5'
      },
      medium: {
        is: '2.0',
        clan: '2.0'
      },
      heavy: {
        is: '1.5',
        clan: '1.5'
      },
      assault: {
        is: '1.0',
        clan: '1.0'
      },
    }
  }, {
    name: "AMS Effectiveness",
    label: "AMS Overload",
    description: "Increases Anti-Missile System shootdown rate",
    value: "0.75",
    template: "+{}%",
    color: "#377eb8"
  }, {
    name: "Crit Chance Received",
    label: "Reinforced Casing",
    description: "Reduces critical hit against internal structure rate",
    value: "1",
    template: "-{}%",
    color: "#4daf4a"
  }, {
    name: "Internal Structure",
    label: "Skeletal Density",
    description: "Increases internal structure",
    value: "3.1",
    template: "+{}%",
    color: "#984ea3",
    chassisValues: {
      light: {
        is: '4',
        clan: '4'
      },
      medium: {
        is: '3.5',
        clan: '3.5'
      },
      heavy: {
        is: '2.5',
        clan: '2.5'
      },
      assault: {
        is: '1.5',
        clan: '1.5'
      },
    }
  }, {
    name: "Fall Damage",
    label: "Shock Absorbtion",
    description: "Reduces damage taken from falls",
    value: "10",
    template: "-{}%",
    color: "#ff7f00"
  },
  /*
  ==========================================
                    MOBILITY
  ==========================================
  */
  {
    name: "Acceleration",
    label: "Kinetic Burst",
    description: "Increases acceleration",
    value: "3.5",
    template: "+{}%",
    color: "#e41a1c"
  }, {
    name: "Deceleration",
    label: "Hard Brake",
    description: "Increases deceleration",
    value: "3.5",
    template: "+{}%",
    color: "#377eb8"
  }, {
    name: "Max Torso Inclination",
    label: "Torso Pitch",
    description: "Increases the degree to which a 'mech can incline its torso",
    value: "2",
    template: "+{}%",
    color: "#4daf4a"
  }, {
    name: "Max Arm Inclination",
    label: "",
    description: "",
    value: "",
    template: "+{}%",
    color: "#984ea3"
  }, {
    name: "Torso Twist Speed",
    label: "Torso Speed",
    description: "Increases the speed with which a 'mech can turn its torso",
    value: "3.5",
    template: "+{}%",
    color: "#ff7f00",
    chassisValues: {
      light: {
        is: '5',
        clan: '5'
      },
      medium: {
        is: '4',
        clan: '4'
      },
      heavy: {
        is: '3.5',
        clan: '3.5'
      },
      assault: {
        is: '3.5',
        clan: '3.5'
      },
    }
  }, {
    name: "Max Torso Twist",
    label: "Torso Yaw",
    description: "Increases the maximum degree of a 'mechs torso twist",
    value: "2",
    template: "+{}%",
    color: "#ffff33"
  }, {
    name: "Turn Speed",
    label: "Anchor Turn",
    description: "Increases the 'mechs turning speed",
    value: "5",
    template: "+{}%",
    color: "#a65628"
  }, {
    name: "Max Speed",
    label: "Speed Tweak",
    description: "Increases the 'mechs top speed",
    value: "1.5",
    template: "+{}%",
    color: "#f781bf"
  },
  /*
  ==========================================
                  JUMP JETS
  ==========================================
  */
  {
    name: "Jump Jet Heat Reduction",
    label: "Heat Shielding",
    description: "Decreases the heat generated by jump jets",
    value: "6",
    template: "-{}%",
    color: "#e41a1c"
  }, {
    name: "Jump Jet Initial Boost",
    label: "Lift Speed",
    description: "Increases the initial boost of jump jets",
    value: "3",
    template: "+{}%",
    color: "#377eb8"
  }, {
    name: "Jump Jet Forward Thrust",
    label: "Vectoring",
    description: "Increases the forward thrust generated by jump jets",
    value: "25",
    template: "+{}%",
    color: "#4daf4a"
  }, {
    name: "Jump Jet Burn Time",
    label: "Vent Calibration",
    description: "Increases jump jet duration",
    value: "3",
    template: "+{}%",
    color: "#984ea3"
  },
  /*
  ==========================================
                 OPERATIONS
  ==========================================
  */
  {
    name: "Startup Speed",
    label: "Quick Ignition",
    description: "Improves start-up and shut-down speeds",
    value: "7",
    template: "-{}%",
    color: "#e41a1c"
  }, {
    name: "Legged Speed",
    label: "Speed Retention",
    description: "Increases max speed while legged; capped at 50 kph",
    value: "10",
    template: "+{}%",
    color: "#377eb8"
  }, {
    name: "Heat Capacity",
    label: "Heat Containment",
    description: "Increases maximum heat capacity",
    value: "3",
    template: "+{}%",
    color: "#4daf4a"
  }, {
    name: "Hill Climb",
    label: "Hill Climb",
    description: "Decreases the speed loss caused by climbing slopes",
    value: "5",
    template: "+{}%",
    color: "#984ea3"
  }, {
    name: "Heat Dissipation",
    label: "Cool Run",
    description: "Increases heat dissipation",
    value: "2",
    template: "+{}%",
    color: "#ff7f00"
  }, {
    name: "Tastier Gyros",
    label: "Improved Gyros",
    description: "Mmmm... gyros",
    value: "17.5",
    template: "-{}%",
    color: "#ffff33"
  },
  /*
  ==========================================
                   SENSORS
  ==========================================
  */
  {
    name: "Target Info Speed",
    label: "Target Info Gathering",
    description: "Decreases time needed for detailed targeting info",
    value: "7",
    template: "+{}%",
    color: "#e41a1c"
  }, {
    name: "Target Retention",
    label: "Target Retention",
    description: "Increases the range at which a targeting lock will be held when the target moves behind the 'mech",
    value: "200",
    template: "+{} m.",
    color: "#377eb8"
  }, {
    name: "Sensor Range",
    label: "Sensor Range",
    description: "Increases the range of targeting sensors",
    value: "7",
    template: "+{}%",
    color: "#4daf4a"
  }, {
    name: "Target Lock Decay",
    label: "Target Decay",
    description: "Increases the time a targeting lock will be held when the target moves out line-of-sight",
    value: "0.7",
    template: "+{} sec.",
    color: "#984ea3"
  }, {
    name: "Zoom Magnifier",
    label: "Advanced Zoom",
    description: "Adds additional x4 zoom mode",
    value: "1",
    template: "+{}",
    color: "#ff7f00"
  }, {
    name: "Radar Deprivation",
    label: "Radar Deprivation",
    description: "Decreases the time the 'mech will remain targeted when it moves out of line-of-sight",
    value: "20",
    template: "+{}%",
    color: "#ffff33"
  }, {
    name: "Seismic Sensor",
    label: "Seismic Sensor",
    description: "Indicates enemy 'mech movements on the minimap; 'mech must remain stationary",
    value: "100",
    template: "{} m.",
    color: "#a65628"
  }, {
    name: "Enhanced ECM Systems",
    label: "Enhanced ECM",
    description: "Decreases the range at which an ECM-protected 'mech can be targeted; decreases the reactivation cooldown of Stealth Armor",
    value: "22.5",
    template: "+{}%",
    color: "#f781bf"
  },
  /*
  ==========================================
                  AUXILIARY
  ==========================================
  */
  {
    name: "UAV Duration",
    label: "UAV Duration",
    description: "Increases the duration of deployed UAVs",
    value: "10",
    template: "+{} sec.",
    color: "#1f78b4"
  }, {
    name: "UAV Sight Range",
    label: "UAV Range",
    description: "Increases the targeting range of deployed UAVs",
    value: "20",
    template: "+{}%",
    color: "#777777"
  }, {
    name: "Artillery Strike Duration",
    label: "Advanced Salvos",
    description: "Increases the duration of air and artillery strikes",
    value: "15",
    template: "+{}%",
    color: "#33a02c"
  }, {
    name: "Coolshot Effectiveness",
    label: "Enhanced Coolshot",
    description: "Increases heat dissipation of coolshots",
    value: "15",
    template: "+{}%",
    color: "#fb9a99"
  }, {
    name: "UAV Capacity",
    label: "Extra UAV",
    description: "Adds an additional UAV use",
    value: "1",
    template: "+{}",
    color: "#e31a1c"
  }, {
    name: "Point Capture Speed",
    label: "Capture Assist",
    description: "Increases rate of capture of control points",
    value: "5",
    template: "+{}%",
    color: "#b15928"
  }, {
    name: "NARC Velocity and Duration",
    label: "Enhanced NARC",
    description: "Increases NARC beacon projectile speed; increases NARC beacon duration on target",
    value: "10",
    template: "+{}%",
    color: "#ff7f00"
  }, {
    name: "Additional Air / Arty Strike",
    label: "Expanded Reserves",
    description: "Adds an additional air or artillery strike",
    value: "1",
    template: "+{}",
    color: "#cab2d6"
  }, {
    name: "Air / Arty Strike Accuracy",
    label: "Enhanced Spotting",
    description: "Increases the accuracy of air and artillery strikes",
    value: "20",
    template: "-{}%",
    color: "#fdbf6f"
  }, {
    name: "Additional Consumable Slot",
    label: "Consumable Slot",
    description: "Adds an additional consumable slot",
    value: "1",
    template: "+{}",
    color: "#ffff99"
  }, {
    name: "Coolant Reserves",
    label: "Coolant Reserves",
    description: "Adds an additional coolshot use",
    value: "1",
    template: "+{}",
    color: "#6a3d9a"
  }, {
    name: "Coolshot Cooldown",
    label: "Coolant Cooldown",
    description: "Reduces cooldown duration on coolshots",
    value: "25",
    template: "-{}%",
    color: "#b2df8a"
  }
]
