export let attributeMap = {
  "Weapon Range": "+{}%",
  "Laser Duration": "-{}%",
  "Weapon Velocity": "+{}%",
  "Weapon Cooldown": "-{}%",
  "Missile Crit Damage": "+{}%",
  "Gauss Held Time": "+{} sec.",
  "Armor": "+{}%",
  "AMS Effectiveness": "+{}%",
  "Weapon Heat Gen": "-{}%",
  "Ballistic Ammo": "+{}",
  "Missile Ammo": "+{}",
  "Missile Spread": "+{}%",
  "LBX Spread": "-{}%",
  "Fall Damage": "-{}%",
  "UAC Jam Chance": "-{}%",
  "Crit Chance (Received)": "-{}%",
  "Internal Structure": "+{}%",
  "Acceleration": "+{}%",
  "Deceleration": "+{}%",
  "Max Torso Inclination": "+{}%",
  "Max Arm Inclination": "+{}%",
  "Torso Twist Speed": "+{}%",
  "Max Torso Twist": "+{}%",
  "Turn Speed": "+{}%",
  "Max Speed": "+{}%",
  "Jump Jet Heat Reduction": "-{}%",
  "Jump Jet Initial Boost": "+{}%",
  "Jump Jet Forward Thrust": "+{}%",
  "Jump Jet Burn Time": "+{}%",
  "Tastier Gyros": "-{}%",
  "Startup Speed": "-{}%",
  "Legged Speed": "+{}%",
  "Heat Capacity": "+{}%",
  "Hill Climb": "+{}%",
  "Heat Dissipation": "+{}%",
  "Target Info Speed": "+{}%",
  "Target Retention": "+{} m.",
  "Sensor Range": "+{}%",
  "Target Lock Decay": "+{} sec.",
  "Zoom Magnifier": "+{}",
  "Radar Deprivation": "+{}%",
  "Seismic Sensor": "{} m.",
  "ECM Range": "+{}%",
  "Consumable Slots": "+{}",
  "UAV Duration": "+{} sec.",
  "UAV Sight Range": "+{}%",
  "Artillery Strike Duration": "+{}%",
  "Coolshot Effectiveness": "+{}%",
  "UAV Capacity": "+{}",
  "Point Capture Speed": "+{}%",
  "NARC Velocity and Duration": "+{}%",
  "Additional Air/Arty Strike": "+{}",
  "Air/Arty Strike Accuracy": "-{}%",
  "Additional Consumable Slot": "+{}",
  "Rate of Capture": "+{}%",
  "Coolant Reserves": "+{}",
  "Coolshot Cooldown": "-{}%"
}
